// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByEws9K74XwSIlqQKLHDnqxMQ08TANsRE',
    appId: '1:491502125972:web:e623178e65511e29450581',
    messagingSenderId: '491502125972',
    projectId: 'bemichat-a8e4d',
    authDomain: 'bemichat-a8e4d.firebaseapp.com',
    storageBucket: 'bemichat-a8e4d.firebasestorage.app',
    measurementId: 'G-NVEM1PGN36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFjzpCsur2iJkTO9f6APcUBk6rU6PBWfo',
    appId: '1:491502125972:android:f7d42d1ab2dcb02b450581',
    messagingSenderId: '491502125972',
    projectId: 'bemichat-a8e4d',
    storageBucket: 'bemichat-a8e4d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByEws9K74XwSIlqQKLHDnqxMQ08TANsRE',
    appId: '1:491502125972:web:d51f964959c771ce450581',
    messagingSenderId: '491502125972',
    projectId: 'bemichat-a8e4d',
    authDomain: 'bemichat-a8e4d.firebaseapp.com',
    storageBucket: 'bemichat-a8e4d.firebasestorage.app',
    measurementId: 'G-6G35BP4JCW',
  );
}
